### ISSUE TITLE
CarlaUE4.sh not start up correctly

### ISSUE THREAD

**Issue by TauJiang** [atinfinity/carla_ros_bridge_docker#8] opened 2022-12-23 21:02 UTC
HI Merry Christmas,

![image](https://user-images.githubusercontent.com/43357466/209405218-2ad7329d-749f-47d3-a1ee-31de5bd61342.png)
 when I try to run Carla in the docker CLI, it was not able to do it without error, not sure why

**Comment by atinfinity** [comment] 2022-12-25 04:00
I tried to reproduce on the following environment.

- Ubuntu 22.04
- Docker 20.10.21
- nvidia-docker2 2.11.0
- nvidia-driver 520.61.05

But, I could not reproduce. Please investigate yourself.  
And, the following tickets may help you in your investigation.
<https://github.com/carla-simulator/carla/issues>

So, I closed this issue.

**Closed as completed by atinfinity** 2022-12-25 04:00 UTC

**Comment by TauJiang** [comment] 2022-12-25 05:00
Well thanks.
